spring:
  application:
    name: hair_mvp

  config:
    import: "optional:file:.env[.properties]"  # .env ?? ?? ??

  main:
    allow-bean-definition-overriding: true

  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: ${DB_URL}
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

jwt:
  secret-key: ${SECRET_KEY}
  access-key-expiration-s: ${ACCESS_KEY_EXPIRATION_SECONDS}
  refresh-key-expiration-s: ${REFRESH_KEY_EXPIRATION_SECONDS}

oauth:
  google-client-id: ${GOOGLE_CLIENT_ID}
  google-client-secret: ${GOOGLE_CLIENT_SECRET}

thread:
  pool:
    core-pool-size: 4
    queue-capacity: 50
    max-pool-size: 8

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

kakaopay:
  secret-key: ${KAKAO_SECRET_KEY}
  cid: ${CID}

